kind = "mobile"
previewPath = "/"
title = "WIB"
version = "1.0.0"
id = "artifacts/wib"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21759

[services.development]
run = "pnpm --filter @workspace/wib run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wib", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/wib", "run", "serve" ]

[services.env]
PORT = "21759"
BASE_PATH = "/"
